server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: nonameplz.mybatis.entity

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/
    username: root
    password: 0721~Forever
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com"
    accessKeyId: LTAI5tJB6Vc8LfT993Kd37N4
    accessKeySecret: JkV5wMcCBv2rZpZGue7Q0gw1Q6krFC
    bucketName: web-image-container

#spring??????
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug